### ISSUE TITLE
'7501c73d0c4dc' is a valid phone number

### ISSUE THREAD

**Issue by alarv** [grantila/awesome-phonenumber#114] opened 2024-01-11 10:44 UTC
This simple example
```javascript
const ap = require('awesome-phonenumber');

const obj = ap.parsePhoneNumber('7501c73d0c4dc', { regionCode: 'DE' });

console.log(obj.valid) // returns true
```
returns true. Shouldn't the library validate the number of alphanumeric characters?

**Comment by grantila** [comment] 2024-01-17 09:04
It's intentional by libphonenumber. Duplicate of #100.

**Closed by grantila** 2024-01-17 09:04 UTC
